apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-light-scaledobject
  namespace: danswer
  labels:
    app: celery-worker-light
spec:
  scaleTargetRef:
    name: celery-worker-light
  minReplicaCount: 1
  maxReplicaCount: 15
  triggers:
    - type: redis
      metadata:
        host: "master.redisencrypted.4h4xor.use2.cache.amazonaws.com"
        port: "6379"
        enableTLS: "true"
        listName: vespa_metadata_sync
        listLength: "1" # Scale up as soon as there's a task
        password: "50lbsAuthTokenDanswer"
        databaseIndex: "15"
    - type: redis
      metadata:
        host: "master.redisencrypted.4h4xor.use2.cache.amazonaws.com"
        port: "6379"
        enableTLS: "true"
        listName: vespa_metadata_sync:2
        listLength: "1" # Scale up as soon as there's a task
        password: "50lbsAuthTokenDanswer"
        databaseIndex: "15"
    - type: redis
      metadata:
        host: "master.redisencrypted.4h4xor.use2.cache.amazonaws.com"
        port: "6379"
        enableTLS: "true"
        listName: vespa_metadata_sync:3
        listLength: "1" # Scale up as soon as there's a task
        password: "50lbsAuthTokenDanswer"
        databaseIndex: "15"
    - type: redis
      metadata:
        host: "master.redisencrypted.4h4xor.use2.cache.amazonaws.com"
        port: "6379"
        enableTLS: "true"
        listName: connector_deletion
        listLength: "1" # Scale up as soon as there's a task
        password: "50lbsAuthTokenDanswer"
        databaseIndex: "15"
    - type: redis
      metadata:
        host: "master.redisencrypted.4h4xor.use2.cache.amazonaws.com"
        port: "6379"
        enableTLS: "true"
        listName: connector_deletion:2
        listLength: "1" # Scale up as soon as there's a task
        password: "50lbsAuthTokenDanswer"
        databaseIndex: "15"
